import { Anchor, ArrowRight, Brain, Flower2, PenLine, Sparkles, Wind } from "lucide-react";
import { useState } from "react";
import { Link } from "wouter";

const practices = [
  { icon: Wind, type: "60 seconds", title: "Longer exhale", body: "A short breathing reset that leaves a little more room inside the moment.", tint: "bg-[#EEF0FF] text-[#596BD7]", steps: ["Let your shoulders drop.", "Breathe in gently for four.", "Breathe out slowly for six.", "Repeat three times at your own pace."] },
  { icon: Anchor, type: "2 minutes", title: "5–4–3–2–1 grounding", body: "Bring your attention to the ordinary details around you, one sense at a time.", tint: "bg-[#EEF7F0] text-[#5A8A68]", steps: ["Name five things you can see.", "Notice four things you can feel.", "Listen for three things you can hear.", "Name two scents and one taste."] },
  { icon: Brain, type: "5 minutes", title: "Soften a busy thought", body: "Make room between you and a thought by noticing it with curiosity, not judgment.", tint: "bg-[#FFF3EF] text-[#CB7667]", steps: ["Write the thought down exactly as it appears.", "Add: ‘I’m noticing the thought that…’", "Ask what a kinder, balanced view might include.", "Choose one caring next step."] },
  { icon: Flower2, type: "3 minutes", title: "Name what matters", body: "Reconnect with a small value or quality you want to carry through today.", tint: "bg-[#FFF8E7] text-[#B88723]", steps: ["Choose one word: kindness, courage, rest, or connection.", "Notice one tiny way that word could show up.", "Let that be enough for today."] },
];

export default function Library() {
  const [active, setActive] = useState<number | null>(null);
  return <div className="mx-auto max-w-6xl space-y-8"><section className="rounded-[28px] bg-[#EAF3EC] px-6 py-8 sm:px-8 lg:px-10"><div className="max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-white/75 px-3 py-1.5 text-xs font-bold text-[#52785D]"><Sparkles className="size-3.5" /> Reflection & growth library</span><h1 className="mt-5 font-display text-3xl font-extrabold tracking-[-0.045em] text-[#294334] sm:text-4xl">Small practices for real moments.</h1><p className="mt-3 text-sm leading-6 text-[#547060] sm:text-base">There is no need to do everything. Choose one practice that meets the weather you are in.</p></div></section>
    <section><div className="mb-5 flex items-end justify-between gap-4"><div><p className="font-display text-xl font-extrabold tracking-[-0.03em]">Try a gentle practice</p><p className="mt-1 text-sm text-[#73798B]">Simple, evidence-informed tools with no pressure to get them “right.”</p></div></div><div className="grid gap-4 md:grid-cols-2">{practices.map((practice, index) => { const Icon = practice.icon; const expanded = active === index; return <article key={practice.title} className="overflow-hidden rounded-[24px] border border-[#E8E8E2] bg-white p-5 soft-shadow"><div className="flex items-start justify-between gap-3"><span className={`grid size-11 place-items-center rounded-2xl ${practice.tint}`}><Icon className="size-5" /></span><span className="rounded-full bg-[#F7F7F4] px-3 py-1 text-[11px] font-bold text-[#818796]">{practice.type}</span></div><h2 className="mt-5 font-display text-lg font-extrabold tracking-[-0.025em] text-[#2D3142]">{practice.title}</h2><p className="mt-2 text-sm leading-6 text-[#73798B]">{practice.body}</p><button onClick={() => setActive(expanded ? null : index)} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#5568D3] hover:underline">{expanded ? "Close practice" : "Open practice"}<ArrowRight className={`size-4 transition-transform ${expanded ? "rotate-90" : ""}`} /></button>{expanded && <ol className="mt-5 space-y-3 border-t border-[#F0F0ED] pt-5">{practice.steps.map((step, stepIndex) => <li key={step} className="flex gap-3 text-sm leading-5 text-[#596070]"><span className="grid size-5 shrink-0 place-items-center rounded-full bg-[#EEF0FF] text-[11px] font-bold text-[#5B6EE1]">{stepIndex + 1}</span>{step}</li>)}</ol>}</article>; })}</div></section>
    <section className="grid gap-5 rounded-[26px] border border-[#E8E8E2] bg-white p-6 soft-shadow md:grid-cols-[auto_1fr_auto] md:items-center"><span className="grid size-12 place-items-center rounded-2xl bg-[#FFF1ED] text-[#D77A69]"><PenLine className="size-5" /></span><div><p className="font-display text-lg font-extrabold tracking-[-0.025em]">Need a place to put your thoughts?</p><p className="mt-1 text-sm leading-6 text-[#73798B]">Start with a single sentence. Your companion can help you reflect without judgment.</p></div><Link href="/chat" className="inline-flex h-11 items-center justify-center rounded-xl bg-[#5B6EE1] px-5 text-sm font-bold text-white hover:bg-[#4C5FCB]">Start reflecting</Link></section>
  </div>;
}
