import { ArrowUpRight, CheckCircle2, FileText, HeartHandshake, LockKeyhole, Search } from "lucide-react";

const directories = [
  { name: "Find a helpline", description: "Find free and confidential support lines across countries and regions.", url: "https://findahelpline.com/" },
  { name: "Psychology Today", description: "Browse licensed professionals by location and specialty in supported regions.", url: "https://www.psychologytoday.com/intl/counsellors" },
  { name: "Inclusive Therapists", description: "Explore a directory centered on culturally responsive care in the U.S.", url: "https://www.inclusivetherapists.com/" },
];

export default function ProfessionalConnect() {
  return <div className="mx-auto max-w-5xl space-y-7"><section className="overflow-hidden rounded-[28px] bg-[#F1F2FF] px-6 py-8 sm:px-9 sm:py-10"><span className="grid size-12 place-items-center rounded-2xl bg-white text-[#5869D5]"><HeartHandshake className="size-6" /></span><h1 className="mt-6 max-w-2xl font-display text-3xl font-extrabold tracking-[-0.045em] text-[#333D7D] sm:text-4xl">When you want a professional beside you.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#58638D] sm:text-base">MindBridge can help you begin the search. Professional care offers a different kind of support—and you deserve a good fit.</p></section>
    <section><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#EEF7F0] text-[#5A8A68]"><Search className="size-5" /></span><div><p className="font-display text-xl font-extrabold tracking-[-0.03em]">Explore reputable directories</p><p className="text-sm text-[#73798B]">Each directory opens in a new tab. Availability, pricing, and credentials are managed by the directory provider.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-3">{directories.map(directory => <a key={directory.name} href={directory.url} target="_blank" rel="noreferrer" className="rounded-[22px] border border-[#E8E8E2] bg-white p-5 transition-transform hover:-translate-y-0.5 soft-shadow"><p className="font-display text-lg font-extrabold tracking-[-0.025em] text-[#2D3142]">{directory.name}</p><p className="mt-2 min-h-15 text-sm leading-6 text-[#73798B]">{directory.description}</p><span className="mt-5 inline-flex items-center gap-1.5 text-sm font-bold text-[#5568D3]">Open directory <ArrowUpRight className="size-4" /></span></a>)}</div></section>
    <section className="grid gap-5 rounded-[26px] border border-[#E8E8E2] bg-white p-6 soft-shadow md:grid-cols-[auto_1fr]"><span className="grid size-12 place-items-center rounded-2xl bg-[#FFF4E5] text-[#BA7119]"><FileText className="size-5" /></span><div><p className="font-display text-xl font-extrabold tracking-[-0.03em]">Bring your story on your terms</p><p className="mt-2 text-sm leading-6 text-[#697083]">A future MindBridge sharing tool should always let you review the exact content before sharing. This version keeps your check-ins and conversations inside your private account; it does not automatically send them to any provider.</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs font-bold text-[#5F6B73]"><span className="inline-flex items-center gap-1.5"><CheckCircle2 className="size-4 text-[#7FA88F]" /> No automatic sharing</span><span className="inline-flex items-center gap-1.5"><LockKeyhole className="size-4 text-[#7FA88F]" /> Consent before disclosure</span></div></div></section>
  </div>;
}
